version: "3"

vars:
  HOST:
    sh: hostname

tasks:

  ### BUILD ###

  build:
    cmds:
      - task: build.nixos
      - task: build.darwin
      - task: build.home

  build.nixos:
    internal: true
    platforms:
      - linux
    cmds:
      - sudo nixos-rebuild --flake .#{{.HOST}} build --show-trace

  build.darwin:
    internal: true
    platforms:
      - darwin
    cmds:
      - sudo darwin-rebuild --flake ".#{{.HOST}}" build --show-trace

  build.home:
    internal: true
    cmds:
      - home-manager --flake .#{{.HOST}} build --show-trace

  ### SWITCH ###

  switch:
    cmds:
      - task: switch.nixos
      - task: switch.darwin
      - task: switch.home

  switch.nixos:
    internal: true
    platforms:
      - linux
    cmds:
      - sudo nixos-rebuild --flake .#{{.HOST}} switch --show-trace

  switch.darwin:
    internal: true
    platforms:
      - darwin
    cmds:
      - sudo darwin-rebuild --flake ".#{{.HOST}}" switch --show-trace

  switch.home:
    internal: true
    cmds:
      - home-manager --flake .#{{.HOST}} switch --show-trace

  ### TEST ###

  test:
    cmds:
      - task: test.nixos
      - task: test.darwin

  test.nixos:
    internal: true
    platforms:
      - linux
    cmds:
      - sudo nixos-rebuild --flake .#{{.HOST}} test --show-trace

  test.darwin:
    internal: true
    platforms:
      - darwin
    cmds:
      - sudo darwin-rebuild --flake ".#{{.HOST}}" test --show-trace

  ### NEWS ###

  news:
    cmds:
      - task: news.home

  news.home:
    internal: true
    cmds:
      - home-manager news

  ### Utils ###

  update:
    cmds:
      - nix flake update

  gc:
    cmds:
      - nix-collect-garbage --delete-older-than 14d
      - nix store gc
