version: "3"

vars:
  HOST:
    sh: hostname

tasks:
  # Alias

  darwin:
    deps: [update]
    cmds:
      - task: switch.darwin
      - task: switch.home
      - task: gc
      - task: cache.nix

  nixos:
    deps: [update]
    cmds:
      - task: switch.system
      - task: switch.home
      - task: gc
      - task: cache.nix

  # Utils

  update:
    cmds:
      - nix flake update

  gc:
    cmds:
      - nix store gc

  # NixOS System

  build.system:
    cmds:
      - sudo nixos-rebuild --flake .#{{.HOST}} build

  switch.system:
    cmds:
      - sudo nixos-rebuild --flake .#{{.HOST}} switch --show-trace

  test.system:
    cmds:
      - sudo nixos-rebuild --flake .#{{.HOST}} test

  # Home Manager

  build.home:
    cmds:
      - home-manager --flake .#{{.HOST}} build

  switch.home:
    cmds:
      - home-manager --flake .#{{.HOST}} switch

  news.home:
    cmds:
      - home-manager news

  # Nix Darwin

  build.darwin:
    cmds:
      - darwin-rebuild --flake ".#{{.HOST}}" build

  switch.darwin:
    cmds:
      - darwin-rebuild --flake ".#{{.HOST}}" switch --show-trace

  # 
  cache.nix:
    cmds:
      - mkdir -p .cache
      - nix search nixpkgs "^" --json > .cache/packages.json
